# This rule is not used by the project namespace-quota-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to quota.dev.operator resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: namespace-quota-operator
    app.kubernetes.io/managed-by: kustomize
  name: quotaprofile-viewer-role
rules:
- apiGroups:
  - quota.dev.operator
  resources:
  - quotaprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - quota.dev.operator
  resources:
  - quotaprofiles/status
  verbs:
  - get
