---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - quota.dev.operator
  resources:
  - quotaprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quota.dev.operator
  resources:
  - quotaprofiles/finalizers
  verbs:
  - update
- apiGroups:
  - quota.dev.operator
  resources:
  - quotaprofiles/status
  verbs:
  - get
  - patch
  - update
