apiVersion: quota.dev.operator/v1alpha1
kind: QuotaProfile
metadata:
  labels:
    app.kubernetes.io/name: namespace-quota-operator
    app.kubernetes.io/managed-by: kustomize
  name: quotaprofile-sample-2
  namespace: default
spec:
  namespaceSelector:
    matchLabels:
      env: dev
  precedence: 1000
  resourceQuotaSpecs:
  -   hard:
        requests.cpu: "1"
        requests.memory: "1Gi"
        limits.cpu: "2"
        limits.memory: "2Gi"
  limitRangeSpecs:
  - limits:
    - default: # this section defines default limits
        cpu: 500m
      defaultRequest: # this section defines default requests
        cpu: 500m
      max: # max and min define the limit range
        cpu: "1"
      min:
        cpu: 100m
      type: Container
